export const PRODUCT_COLORS: string[] = [
    'bg-amber-500',
    'bg-orange-500',
    'bg-red-500',
    'bg-pink-500',
    'bg-purple-500',
    'bg-indigo-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-teal-500',
    'bg-cyan-500'
];

export const TRANSLATIONS = {
    en: {
        appTitle: "Ryan's Bakery",
        appSubtitle: "Water Temperature Tracker",
        appDescription: "\"Perfect Water Temp, Predictable Final Dough.\"",
        modelReady: "Model Ready",
        selectProduct: "Select Product",
        scrollToSelect: "Scroll to select",
        calculatorTitle: "Calculate Water Temp",
        enterData: "Enter variables",
        calcInstruction: "Fill Out Boxes, Generate the Water Temp for Mixing",
        targetWaterTemp: "Suggested Water Temp for Mixing.",
        calculateButton: "Calculate Water Temp",
        historyTitle: "MLR Training History",
        historyList: "Recorded Sessions",
        entries: "Entries",
        noData: "No training data yet.",
        addBakesHint: "Add previous bakes to train the model.",
        yourProducts: "Your Products",
        friction: "Friction",
        date: "Date",
        // Field Labels
        room: "Room Temp",
        flour: "Flour Temp",
        levain: "Levain Temp",
        target: "Target FD Temp",
        mix: "Mix Time", // Expanded for clarity in calc
        hydration: "Hydration (water/flour)",
        water: "Actual Water Temp",
        final: "FD Temp",
        mixShort: "Mix", // For table headers
        hydrShort: "Hydr %",
        mlrTraining: "MLR Training",
        sessions: "Total Session",
        model: "Model",
        coefficients: "Coefficients",
        frictionPerMin: "Friction/min",
        hydrationPercent: "Hydration/%",
        quality: "Quality",
        fit: "Fit",
        // Documentation
        aboutTitle: "User Guide",
        aboutContent: "Ryan's Bakery Water Temperature Tracker **ensures consistent dough by calculating the precise water temperature needed.** It uses Multiple Linear Regression (MLR) to learn from your past baking sessions, adapting to your specific environment and ingredients.",
        howToUseTitle: "How to Use",
        step1Title: "Select Product",
        step1Content: "Scroll the wheel to select a dough type.",
        step2Title: "Calculate Temp",
        step2Content: "Enter current conditions (Room, Flour, etc.) to get the Target Water Temp.",
        step3Title: "Record Session",
        step3Content: "After mixing, use 'Add Practical session Data' to log the actual results to train the MLR model.",
        step4Title: "Export Data",
        step4Content: "Download your baking history as a CSV file.",
        step5Title: "Manage Products",
        step5Content: "Add, rename, reorder, or delete products below.",
        // Field Labels
        trainingStatus: "Training Status",
        statusLabel: "Status",
        reliabilityLabel: "Fit Reliability",
        standardFormula: "Standard Formula",
        mlrTrained: "MLR Trained!",
        // MLR Logic
        mlrLogicTitle: "MLR Logic",
        mlrStep1Title: "Data Collection & 'Waiting' State",
        mlrStep1Content: "The app needs data to start. For a new product, you'll see a 'Waiting...' status until your first bake is recorded.",
        mlrStep2Title: "Standard Formula (Learning Phase)",
        mlrStep2Content: "With 1-2 sessions, the status is 'Standard Formula (Learning: X/3)'. The app uses a base formula while calculating your unique average Friction.",
        mlrStep3Title: "MLR Trained! (Pattern Recognition)",
        mlrStep3Content: "With 3+ sessions, 'MLR Trained!' activates. Multiple Linear Regression is used to analyze how variables like Mix Time or Hydration subtly impact heat.",
        mlrStep4Title: "Fit Reliability Score",
        mlrStep4Content: "Check your R² score: EXCELLENT (≥0.9), GOOD (≥0.7), or LEARNING (<0.7). This tells you how accurately the model matches your specific kitchen's environment.",
        showHistory: "Show History",
        hideHistory: "Hide History",
        showProduct: "Show Product",
        hideProduct: "Hide Product",
        showDetails: "Show Details",
        hideDetails: "Hide Details",
    },
    zh: {
        appTitle: "Ryan's Bakery",
        appSubtitle: "水溫追蹤器",
        appDescription: "計算最佳水溫，確保麵團品質穩定一致。",
        modelReady: "模型就緒",
        selectProduct: "選擇產品",
        scrollToSelect: "滾動選擇",
        calculatorTitle: "計算水溫",
        enterData: "輸入變數",
        calcInstruction: "填寫各欄位以生成理想水溫",
        targetWaterTemp: "目標水溫",
        calculateButton: "計算水溫",
        historyTitle: "MLR 訓練歷史",
        historyList: "已紀錄場次",
        entries: "條紀錄",
        noData: "暫無訓練數據",
        addBakesHint: "添加過往烘焙紀錄以訓練模型",
        yourProducts: "您的產品",
        friction: "摩擦升溫",
        date: "日期",
        room: "室溫 (Room Temp)",
        flour: "粉溫 (Flour Temp)",
        levain: "酵種溫 (Levain Temp)",
        target: "目標 FD Temp (Target FD Temp)",
        mix: "攪拌時間 (Mix Time)",
        hydration: "含水量 Hydration (water/flour)",
        water: "實際水溫 (Actual Water Temp)",
        final: "麵團終溫 (FD Temp)",
        mixShort: "攪拌",
        hydrShort: "含水%",
        mlrTraining: "MLR 訓練",
        sessions: "總場次",
        model: "模型",
        coefficients: "係數",
        frictionPerMin: "摩擦升溫/分",
        hydrationPercent: "含水量/%",
        quality: "品質",
        fit: "擬合度",
        // Documentation
        aboutTitle: "使用指南",
        aboutContent: "Ryan 的烘焙坊水溫追蹤器通過計算理想水溫，助您製作出品質穩定的麵團。應用利用多元線性回歸 (MLR) 從您的烘焙紀錄中學習，根據環境條件預測最佳水溫。",
        howToUseTitle: "使用說明",
        step1Title: "選擇產品",
        step1Content: "滾動轉輪以選擇麵團類型。",
        step2Title: "計算水溫",
        step2Content: "輸入當前條件（室溫、粉溫等）以獲取目標水溫。",
        step3Title: "紀錄場次",
        step3Content: "攪拌後，點擊「添加場次」紀錄實際結果，以訓練 MLR 模型。",
        step4Title: "匯出數據",
        step4Content: "將您的烘焙歷史下載為 CSV 文件。",
        step5Title: "管理產品",
        step5Content: "在下方添加、重命名、排序或刪除產品。",
        // Field Labels
        trainingStatus: "訓練狀態",
        statusLabel: "狀態",
        reliabilityLabel: "擬合可靠度",
        standardFormula: "標準公式",
        mlrTrained: "MLR 訓練完畢!",
        // MLR Logic
        mlrLogicTitle: "MLR 邏輯",
        mlrStep1Title: "數據收集與「等待」狀態",
        mlrStep1Content: "模型需要數據才能運作。對於新產品，在紀錄第一場烘焙前，您會看到「Waiting...」狀態。",
        mlrStep2Title: "標準公式（學習階段）",
        mlrStep2Content: "累積 1-2 場時，狀態為「Standard Formula (Learning: X/3)」。應用會使用基礎公式，並計算您獨特的平均摩擦係數。",
        mlrStep3Title: "MLR 訓練完畢（模式識別）",
        mlrStep3Content: "累積 3 場後，狀態變為「MLR Trained!」。多元線性回歸模型啟動，分析攪拌時間或含水量如何微妙地影響麵團升溫。",
        mlrStep4Title: "擬合可靠度評價",
        mlrStep4Content: "檢查您的 R² 分數得分：EXCELLENT (≥0.9)、GOOD (≥0.7) 或 LEARNING (<0.7)。這反映了模型對您廚房環境預測的精準程度。",
        showHistory: "顯示歷史",
        hideHistory: "隱藏歷史",
        showProduct: "顯示產品",
        hideProduct: "隱藏產品",
        showDetails: "顯示詳情",
        hideDetails: "隱藏詳情",
    },
    ja: {
        appTitle: "ライアンのベーカリー",
        appSubtitle: "水温トラッカー",
        appDescription: "最適な水温を計算し、安定した生地品質を実現します。",
        modelReady: "モデル準備完了",
        selectProduct: "製品を選択",
        scrollToSelect: "スクロールして選択",
        calculatorTitle: "水温を計算",
        enterData: "変数を入力",
        calcInstruction: "各項目を入力して理想的な水温を算出",
        targetWaterTemp: "目標水温",
        calculateButton: "水温を計算",
        historyTitle: "MLR 学習履歴",
        historyList: "記録されたセッション",
        entries: "件",
        noData: "データがありません",
        addBakesHint: "過去のデータを追加してモデルを学習",
        yourProducts: "製品一覧",
        friction: "摩擦熱",
        date: "日付",
        room: "室温 (Room Temp)",
        flour: "粉温 (Flour Temp)",
        levain: "種温 (Levain Temp)",
        target: "目標 FD Temp (Target FD Temp)",
        mix: "ミキシング (Mix Time)",
        hydration: "加水率 Hydration (water/flour)",
        water: "實際水温 (Actual Water Temp)",
        final: "生地終温 (FD Temp)",
        mixShort: "ミキシング",
        hydrShort: "加水%",
        mlrTraining: "MLR 学習",
        sessions: "総セッション",
        model: "モデル",
        coefficients: "係数",
        frictionPerMin: "摩擦/分",
        hydrationPercent: "加水率/%",
        quality: "品質",
        fit: "適合度",
        // Documentation
        aboutTitle: "ユーザーガイド",
        aboutContent: "Ryan's Bakery 水温トラッカーは、理想的な水温を計算し、安定した生地作りをサポートします。重回歸分析 (MLR) を用いて過去のデータから学習し、環境に応じた最適な水温を予測します。",
        howToUseTitle: "使い方",
        step1Title: "製品を選択",
        step1Content: "ホイールをスクロールして生地タイプを選択します。",
        step2Title: "水温を計算",
        step2Content: "現在の条件（室温、粉温など）を入力し、目標水温を取得します。",
        step3Title: "セッションを記録",
        step3Content: "ミキシング後、「セッションを追加」で結果を記録し、MLRモデルを学習させます。",
        step4Title: "データをエクスポート",
        step4Content: "履歴をCSVファイルとしてダウンロードできます。",
        step5Title: "製品を管理",
        step5Content: "製品の追加、名前変更、並べ替え、削除が可能です。",
        // Field Labels
        trainingStatus: "トレーニングステータス",
        statusLabel: "ステータス",
        reliabilityLabel: "適合信頼度",
        standardFormula: "標準式",
        mlrTrained: "MLR 学習完了!",
        // MLR Logic
        mlrLogicTitle: "MLR ロジック",
        mlrStep1Title: "データ収集と待機状態",
        mlrStep1Content: "モデルにはデータが必要です。新しい製品の場合、最初の記録が行われるまで「Waiting...」と表示されます。",
        mlrStep2Title: "標準式（学習フェーズ）",
        mlrStep2Content: "1〜2回の記録では「Standard Formula (Learning: X/3)」となります。独自平均摩擦熱を算出しつつ、標準的な計算式を使用します。",
        mlrStep3Title: "MLR 学習完了（パターン認識）",
        mlrStep3Content: "3回以上の記録で「MLR Trained!」が起動します。ミキシング時間や加水率などの変数が温度に与える隠れたパターンを重回帰分析で導き出します。",
        mlrStep4Title: "適合信頼度スコア",
        mlrStep4Content: "R²スコアを確認してください：EXCELLENT (≥0.9), GOOD (≥0.7), または LEARNING (<0.7)。モデルがあなたのキッチン環境をどれだけ正確に捉えているかを示します。",
        showHistory: "履歴を表示",
        hideHistory: "履歴を隠す",
        showProduct: "製品を表示",
        hideProduct: "製品を隠す",
        showDetails: "詳細を表示",
        hideDetails: "詳細を隠す",
    }
};
